"""
clone_detector.py — Cross-File Semantic Code Clone Detector
VTU Major Project: AI-Driven Semantic Code Analysis and Automated Software Architecture Modeling System

Unlike a text-diff based duplicate finder, this detects clones by MEANING, not exact text —
two functions with different variable names and formatting but the same underlying logic
will still be flagged, because we compare semantic embeddings (already generated by
src/embedder.py), not raw source strings.

No LLM call involved — purely local vector math (cosine similarity) and clustering.
"""

import sys
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "src"))

from embedder import embed_parsed_result, cosine_similarity

try:
    from sklearn.cluster import DBSCAN
    import numpy as np
    HAS_SKLEARN = True
except ImportError:
    HAS_SKLEARN = False


def collect_embeddings_across_files(parsed_files):
    """
    Runs embed_parsed_result on every parsed file and tags each embedding
    with which file it came from, so clones across DIFFERENT files can be
    detected, not just within a single file.
    """
    all_items = []
    for parsed in parsed_files:
        items = embed_parsed_result(parsed)
        for item in items:
            item["file"] = parsed.get("file", "unknown")
            all_items.append(item)
    return all_items


def find_clone_pairs(parsed_files, threshold=0.85):
    """
    Compares every function/class pair ACROSS all uploaded files and flags
    pairs whose semantic similarity exceeds the threshold as likely clones.

    Returns a list of dicts sorted by similarity, highest first:
    {a_name, a_file, a_line, b_name, b_file, b_line, similarity}
    """
    items = collect_embeddings_across_files(parsed_files)
    clone_pairs = []

    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            a, b = items[i], items[j]
            sim = cosine_similarity(a["embedding"], b["embedding"])
            if sim >= threshold:
                clone_pairs.append({
                    "a_name": a["name"], "a_file": a["file"], "a_line": a["line"],
                    "b_name": b["name"], "b_file": b["file"], "b_line": b["line"],
                    "similarity": round(sim, 4)
                })

    clone_pairs.sort(key=lambda x: x["similarity"], reverse=True)
    return clone_pairs


def cluster_clone_families(parsed_files, threshold=0.85, min_samples=2):
    """
    Groups functions into clone FAMILIES (not just pairs) using DBSCAN over
    the embedding space. Useful when 3+ functions are all near-duplicates of
    each other — a pairwise list alone would be repetitive and harder to read.

    Falls back gracefully with a message if scikit-learn isn't installed.
    """
    if not HAS_SKLEARN:
        return {"error": "scikit-learn not installed. Run: pip install scikit-learn"}

    items = collect_embeddings_across_files(parsed_files)
    if len(items) < 2:
        return {"clusters": [], "note": "Not enough functions/classes to cluster."}

    vectors = np.array([item["embedding"] for item in items])
    # DBSCAN eps is a distance threshold; convert similarity threshold to a
    # rough cosine-distance equivalent (1 - similarity).
    eps = 1 - threshold
    labels = DBSCAN(eps=eps, min_samples=min_samples, metric="cosine").fit_predict(vectors)

    clusters = {}
    for item, label in zip(items, labels):
        if label == -1:
            continue  # noise point, not part of any clone family
        clusters.setdefault(int(label), []).append({
            "name": item["name"], "file": item["file"], "line": item["line"]
        })

    # Only keep clusters with 2+ members (a "family" of at least a pair)
    result = [members for members in clusters.values() if len(members) >= 2]
    return {"clusters": result, "total_families": len(result)}


def summarize_clones(parsed_files, threshold=0.85):
    """
    High-level summary used by the UI: pair list + family clusters + a
    simple duplication score (% of functions involved in at least one clone).
    """
    pairs = find_clone_pairs(parsed_files, threshold)
    families = cluster_clone_families(parsed_files, threshold)

    all_items = collect_embeddings_across_files(parsed_files)
    total = len(all_items)
    involved_names = set()
    for p in pairs:
        involved_names.add((p["a_name"], p["a_file"]))
        involved_names.add((p["b_name"], p["b_file"]))

    duplication_pct = round(100 * len(involved_names) / total, 1) if total else 0.0

    return {
        "total_functions_classes": total,
        "clone_pairs": pairs,
        "clone_families": families,
        "duplication_percentage": duplication_pct
    }


if __name__ == "__main__":
    # Quick manual test against sample_project.py duplicated against itself
    # (simulates a two-file project with identical logic in both)
    sys.path.insert(0, BASE_DIR)
    from src.parser import parse_file

    sample_path = os.path.join(BASE_DIR, "sample_project.py")
    parsed_a = parse_file(sample_path)
    parsed_b = parse_file(sample_path)  # same file "twice" = guaranteed clones

    summary = summarize_clones([parsed_a, parsed_b], threshold=0.85)
    print(f"Total functions/classes scanned: {summary['total_functions_classes']}")
    print(f"Duplication percentage: {summary['duplication_percentage']}%")
    print(f"\nTop clone pairs:")
    for p in summary["clone_pairs"][:5]:
        print(f"  [{p['similarity']}] {p['a_name']} ({p['a_file']}:{p['a_line']}) "
              f"<-> {p['b_name']} ({p['b_file']}:{p['b_line']})")