"""
testgenerator.py — AI-Powered Automatic Test Case Generator
VTU Major Project Feature: Generates pytest test cases for every function using Groq AI.
"""

import os
from groq import Groq
from dotenv import load_dotenv

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, "src", ".env"))

api_key = os.getenv("GROQ_API_KEY")
if not api_key:
    raise ValueError("GROQ_API_KEY not found! Check src/.env file.")

client = Groq(api_key=api_key)
MODEL  = "llama-3.3-70b-versatile"


def generate_test_for_function(func: dict, source_code: str, file_name: str) -> str:
    """Generate pytest test cases for a single function using Groq AI."""
    args_str   = ", ".join(
        f"{a['name']}: {a['type']}" if a.get("type") else a["name"]
        for a in func.get("args", [])
    )
    return_type = func.get("return_type", "")
    complexity  = func.get("complexity", 1)
    cx_label    = func.get("complexity_label", "low")
    docstring   = func.get("docstring", "")
    is_async    = func.get("is_async", False)

    prompt = f"""You are an expert Python test engineer writing pytest test cases for a VTU major project.

File: {file_name}
Function: {'async ' if is_async else ''}def {func['name']}({args_str}){' -> ' + return_type if return_type else ''}
Cyclomatic complexity: {complexity} ({cx_label})
Docstring: {docstring or 'None'}

Source code:
```python
{source_code[:2000]}
```

Generate comprehensive pytest test cases for the function '{func['name']}' only.

Rules:
1. Write at least 3 test cases: happy path, edge case, error/exception case
2. If complexity is high (>7), write more tests covering each branch
3. Use descriptive test function names like test_{func['name']}_returns_correct_value
4. Add a comment to each test explaining what it tests
5. Use pytest.raises for exception tests
6. If async, use pytest.mark.asyncio
7. Import only what is needed

Return ONLY valid Python test code. No explanation. No markdown fences."""

    response = client.chat.completions.create(
        model=MODEL,
        max_tokens=800,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()


def generate_tests_for_file(parsed: dict, source_code: str) -> str:
    """Generate a complete pytest test file for all functions in the parsed module."""
    file_name   = os.path.basename(parsed["file"])
    module_name = file_name.replace(".py", "")

    header = f'''"""
Auto-generated test suite for {file_name}
Generated by: AI-Driven Semantic Code Analyzer
VTU Major Project — Automated Test Generation Feature

Run with: pytest test_{module_name}.py -v
"""

import pytest
from {module_name} import *
'''

    all_tests = [header]
    for func in parsed.get("functions", []):
        if func["name"].startswith("__") and func["name"].endswith("__"):
            continue
        print(f"  Generating tests for: {func['name']}...")
        test_code = generate_test_for_function(func, source_code, file_name)
        all_tests.append(f"\n# ── Tests for {func['name']}() ──────────────────\n")
        all_tests.append(test_code)

    return "\n".join(all_tests)


def get_test_summary(test_code: str) -> dict:
    """Count test functions and types in generated test code."""
    lines         = test_code.split("\n")
    test_fns      = [l for l in lines if l.strip().startswith("def test_")]
    async_tests   = [l for l in lines if "async def test_" in l]
    raises_tests  = [l for l in lines if "pytest.raises" in l]
    return {
        "total_tests":     len(test_fns),
        "async_tests":     len(async_tests),
        "exception_tests": len(raises_tests),
    }